package contract

func runAuthCatalog() map[string]map[string]any {
	return map[string]map[string]any{
		"lexicon/app.cerulia.authSessionParticipant.json": permissionSetDoc(
			"app.cerulia.authSessionParticipant",
			"app.cerulia.rpc.getSessionView",
			"app.cerulia.rpc.joinSession",
			"app.cerulia.rpc.leaveSession",
			"app.cerulia.rpc.updateCharacterState",
			"app.cerulia.rpc.sendMessage",
			"app.cerulia.rpc.rollDice",
		),
		"lexicon/app.cerulia.authSecretOperator.json": permissionSetDoc(
			"app.cerulia.authSecretOperator",
			"app.cerulia.rpc.createSecretEnvelope",
			"app.cerulia.rpc.revealSubject",
			"app.cerulia.rpc.redactRecord",
			"app.cerulia.rpc.rotateAudienceKey",
		),
		"lexicon/app.cerulia.authGovernanceOperator.json": permissionSetDoc(
			"app.cerulia.authGovernanceOperator",
			"app.cerulia.rpc.getGovernanceView",
			"app.cerulia.rpc.listSessionPublications",
			"app.cerulia.rpc.createSessionDraft",
			"app.cerulia.rpc.openSession",
			"app.cerulia.rpc.startSession",
			"app.cerulia.rpc.pauseSession",
			"app.cerulia.rpc.resumeSession",
			"app.cerulia.rpc.closeSession",
			"app.cerulia.rpc.archiveSession",
			"app.cerulia.rpc.reopenSession",
			"app.cerulia.rpc.transferAuthority",
			"app.cerulia.rpc.inviteSession",
			"app.cerulia.rpc.cancelInvitation",
			"app.cerulia.rpc.moderateMembership",
			"app.cerulia.rpc.createCharacterInstance",
			"app.cerulia.rpc.updateCharacterState",
			"app.cerulia.rpc.createSecretEnvelope",
			"app.cerulia.rpc.sendMessage",
			"app.cerulia.rpc.rollDice",
			"app.cerulia.rpc.submitAction",
		),
		"lexicon/app.cerulia.authPublicationOperator.json": permissionSetDoc(
			"app.cerulia.authPublicationOperator",
			"app.cerulia.rpc.publishSessionLink",
			"app.cerulia.rpc.retireSessionLink",
		),
		"lexicon/app.cerulia.authAppealOriginator.json": permissionSetDoc(
			"app.cerulia.authAppealOriginator",
			"app.cerulia.rpc.listAppealCases",
			"app.cerulia.rpc.submitAppeal",
			"app.cerulia.rpc.withdrawAppeal",
		),
		"lexicon/app.cerulia.authAppealResolver.json": permissionSetDoc(
			"app.cerulia.authAppealResolver",
			"app.cerulia.rpc.listAppealCases",
			"app.cerulia.rpc.submitAppeal",
			"app.cerulia.rpc.withdrawAppeal",
			"app.cerulia.rpc.reviewAppeal",
			"app.cerulia.rpc.escalateAppeal",
			"app.cerulia.rpc.resolveAppeal",
		),
	}
}
