package contract

func coreCatalog() map[string]map[string]any {
	return map[string]map[string]any{
		"lexicon/app.cerulia.core.world.json": stableRecord(
			"app.cerulia.core.world",
			[]string{"worldId", "title", "defaultRuleProfileRefs", "stewardDids", "revision", "requestId", "createdAt", "updatedAt"},
			map[string]any{
				"worldId":                stringDef(""),
				"title":                  stringDef(""),
				"canonSummary":           stringDef(""),
				"defaultRuleProfileRefs": arrayDef(refDef("app.cerulia.defs#ruleProfileRef")),
				"stewardDids":            arrayDefMin(refDef("app.cerulia.defs#did"), 1),
				"revision":               integerDef(),
				"requestId":              refDef("app.cerulia.defs#requestId"),
				"createdAt":              refDef("app.cerulia.defs#datetime"),
				"updatedAt":              refDef("app.cerulia.defs#datetime"),
			},
		),
		"lexicon/app.cerulia.core.house.json": stableRecord(
			"app.cerulia.core.house",
			[]string{"houseId", "title", "defaultRuleProfileRefs", "defaultReusePolicyKind", "stewardDids", "revision", "requestId", "createdAt", "updatedAt"},
			map[string]any{
				"houseId":                stringDef(""),
				"title":                  stringDef(""),
				"worldRef":               refDef("app.cerulia.defs#worldRef"),
				"defaultRuleProfileRefs": arrayDef(refDef("app.cerulia.defs#ruleProfileRef")),
				"defaultReusePolicyKind": refDef("app.cerulia.defs#reusePolicyKind"),
				"policySummary":          stringDef(""),
				"stewardDids":            arrayDefMin(refDef("app.cerulia.defs#did"), 1),
				"revision":               integerDef(),
				"requestId":              refDef("app.cerulia.defs#requestId"),
				"createdAt":              refDef("app.cerulia.defs#datetime"),
				"updatedAt":              refDef("app.cerulia.defs#datetime"),
			},
		),
		"lexicon/app.cerulia.core.campaign.json": stableRecord(
			"app.cerulia.core.campaign",
			[]string{"campaignId", "title", "visibility", "rulesetNsid", "rulesetManifestRef", "sharedRuleProfileRefs", "defaultReusePolicyKind", "stewardDids", "createdAt", "revision", "requestId", "updatedAt"},
			map[string]any{
				"campaignId":             stringDef(""),
				"title":                  stringDef(""),
				"visibility":             refDef("app.cerulia.defs#visibility"),
				"houseRef":               refDef("app.cerulia.defs#houseRef"),
				"worldRef":               refDef("app.cerulia.defs#worldRef"),
				"rulesetNsid":            refDef("app.cerulia.defs#rulesetNsid"),
				"rulesetManifestRef":     refDef("app.cerulia.defs#rulesetManifestRef"),
				"sharedRuleProfileRefs":  arrayDef(refDef("app.cerulia.defs#ruleProfileRef")),
				"defaultReusePolicyKind": refDef("app.cerulia.defs#reusePolicyKind"),
				"stewardDids":            arrayDefMin(refDef("app.cerulia.defs#did"), 1),
				"createdAt":              refDef("app.cerulia.defs#datetime"),
				"archivedAt":             refDef("app.cerulia.defs#datetime"),
				"revision":               integerDef(),
				"requestId":              refDef("app.cerulia.defs#requestId"),
				"updatedAt":              refDef("app.cerulia.defs#datetime"),
			},
		),
		"lexicon/app.cerulia.core.rulesetManifest.json": stableRecord(
			"app.cerulia.core.rulesetManifest",
			[]string{"rulesetNsid", "manifestVersion", "actionSchemaRefs", "outputSchemaRefs", "resolverRef", "resolverVersion", "capabilityKinds", "publishedAt"},
			map[string]any{
				"rulesetNsid":      refDef("app.cerulia.defs#rulesetNsid"),
				"manifestVersion":  integerDef(),
				"actionSchemaRefs": arrayDef(stringDef("uri")),
				"outputSchemaRefs": arrayDef(stringDef("uri")),
				"resolverRef":      stringDef("uri"),
				"resolverVersion":  integerDef(),
				"capabilityKinds":  arrayDef(stringDef("")),
				"publishedAt":      refDef("app.cerulia.defs#datetime"),
				"retiredAt":        refDef("app.cerulia.defs#datetime"),
			},
		),
		"lexicon/app.cerulia.core.ruleProfile.json": stableRecord(
			"app.cerulia.core.ruleProfile",
			[]string{"baseRulesetNsid", "profileTitle", "scopeKind", "scopeRef", "status", "rulesPatchRef", "approvedByDid", "requestId", "createdAt", "updatedAt"},
			map[string]any{
				"baseRulesetNsid": refDef("app.cerulia.defs#rulesetNsid"),
				"profileTitle":    stringDef(""),
				"scopeKind":       refDef("app.cerulia.defs#ruleProfileScopeKind"),
				"scopeRef":        refDef("app.cerulia.defs#scopeRef"),
				"status":          refDef("app.cerulia.defs#ruleProfileStatus"),
				"effectiveFrom":   refDef("app.cerulia.defs#datetime"),
				"effectiveUntil":  refDef("app.cerulia.defs#datetime"),
				"supersedesRef":   refDef("app.cerulia.defs#ruleProfileRef"),
				"rulesPatchRef":   stringDef("at-uri"),
				"approvedByDid":   refDef("app.cerulia.defs#did"),
				"requestId":       refDef("app.cerulia.defs#requestId"),
				"createdAt":       refDef("app.cerulia.defs#datetime"),
				"updatedAt":       refDef("app.cerulia.defs#datetime"),
			},
		),
		"lexicon/app.cerulia.core.characterSheet.json": stableRecord(
			"app.cerulia.core.characterSheet",
			[]string{"ownerDid", "rulesetNsid", "displayName", "version", "updatedAt"},
			map[string]any{
				"ownerDid":         refDef("app.cerulia.defs#did"),
				"rulesetNsid":      refDef("app.cerulia.defs#rulesetNsid"),
				"displayName":      stringDef(""),
				"portraitRef":      refDef("app.cerulia.defs#assetRef"),
				"publicProfile":    map[string]any{"type": "unknown"},
				"stats":            map[string]any{"type": "unknown"},
				"externalSheetUri": stringDef("uri"),
				"version":          integerDef(),
				"updatedAt":        refDef("app.cerulia.defs#datetime"),
			},
		),
		"lexicon/app.cerulia.core.characterBranch.json": stableRecord(
			"app.cerulia.core.characterBranch",
			[]string{"ownerDid", "baseSheetRef", "branchKind", "branchLabel", "requestId", "revision", "createdAt", "updatedAt", "updatedByDid"},
			map[string]any{
				"ownerDid":           refDef("app.cerulia.defs#did"),
				"baseSheetRef":       refDef("app.cerulia.defs#characterSheetRef"),
				"branchKind":         refDef("app.cerulia.defs#branchKind"),
				"branchLabel":        stringDef(""),
				"overridePayloadRef": stringDef("at-uri"),
				"importedFrom":       stringDef("uri"),
				"sourceRevision":     integerDef(),
				"syncMode":           refDef("app.cerulia.defs#syncMode"),
				"requestId":          refDef("app.cerulia.defs#requestId"),
				"revision":           integerDef(),
				"createdAt":          refDef("app.cerulia.defs#datetime"),
				"updatedAt":          refDef("app.cerulia.defs#datetime"),
				"updatedByDid":       refDef("app.cerulia.defs#did"),
				"retiredAt":          refDef("app.cerulia.defs#datetime"),
			},
		),
		"lexicon/app.cerulia.core.characterConversion.json": appendOnlyRecord(
			"app.cerulia.core.characterConversion",
			[]string{"sourceSheetRef", "sourceSheetVersion", "sourceRulesetManifestRef", "sourceEffectiveRuleProfileRefs", "targetSheetRef", "targetSheetVersion", "targetBranchRef", "targetRulesetManifestRef", "targetEffectiveRuleProfileRefs", "conversionContractRef", "conversionContractVersion", "convertedByDid", "convertedAt", "requestId"},
			map[string]any{
				"sourceSheetRef":                 refDef("app.cerulia.defs#characterSheetRef"),
				"sourceSheetVersion":             integerDef(),
				"sourceBranchRef":                refDef("app.cerulia.defs#characterBranchRef"),
				"sourceEpisodeRefs":              arrayDef(refDef("app.cerulia.defs#characterEpisodeRef")),
				"sourceRulesetManifestRef":       refDef("app.cerulia.defs#rulesetManifestRef"),
				"sourceEffectiveRuleProfileRefs": arrayDef(refDef("app.cerulia.defs#ruleProfileRef")),
				"targetSheetRef":                 refDef("app.cerulia.defs#characterSheetRef"),
				"targetSheetVersion":             integerDef(),
				"targetBranchRef":                refDef("app.cerulia.defs#characterBranchRef"),
				"targetCampaignRef":              refDef("app.cerulia.defs#campaignRef"),
				"targetRulesetManifestRef":       refDef("app.cerulia.defs#rulesetManifestRef"),
				"targetEffectiveRuleProfileRefs": arrayDef(refDef("app.cerulia.defs#ruleProfileRef")),
				"conversionContractRef":          stringDef("uri"),
				"conversionContractVersion":      integerDef(),
				"reuseGrantRef":                  refDef("app.cerulia.defs#reuseGrantRef"),
				"supersedesRef":                  refDef("app.cerulia.defs#characterConversionRef"),
				"convertedByDid":                 refDef("app.cerulia.defs#did"),
				"convertedAt":                    refDef("app.cerulia.defs#datetime"),
				"requestId":                      refDef("app.cerulia.defs#requestId"),
				"note":                           stringDef(""),
			},
		),
		"lexicon/app.cerulia.core.characterAdvancement.json": appendOnlyRecord(
			"app.cerulia.core.characterAdvancement",
			[]string{"characterBranchRef", "advancementKind", "deltaPayloadRef", "approvedByDid", "effectiveAt", "requestId", "createdAt"},
			map[string]any{
				"characterBranchRef": refDef("app.cerulia.defs#characterBranchRef"),
				"sourceRunRef":       refDef("app.cerulia.defs#sourceRunRef"),
				"advancementKind":    refDef("app.cerulia.defs#advancementKind"),
				"deltaPayloadRef":    stringDef("at-uri"),
				"approvedByDid":      refDef("app.cerulia.defs#did"),
				"effectiveAt":        refDef("app.cerulia.defs#datetime"),
				"supersedesRef":      refDef("app.cerulia.defs#characterAdvancementRef"),
				"requestId":          refDef("app.cerulia.defs#requestId"),
				"createdAt":          refDef("app.cerulia.defs#datetime"),
				"note":               stringDef(""),
			},
		),
		"lexicon/app.cerulia.core.characterEpisode.json": appendOnlyRecord(
			"app.cerulia.core.characterEpisode",
			[]string{"characterBranchRef", "rulesetManifestRef", "effectiveRuleProfileRefs", "outcomeSummary", "advancementRefs", "recordedByDid", "createdAt", "requestId"},
			map[string]any{
				"characterBranchRef":       refDef("app.cerulia.defs#characterBranchRef"),
				"campaignRef":              refDef("app.cerulia.defs#campaignRef"),
				"sourceRunRef":             refDef("app.cerulia.defs#sourceRunRef"),
				"scenarioLabel":            stringDef(""),
				"rulesetManifestRef":       refDef("app.cerulia.defs#rulesetManifestRef"),
				"effectiveRuleProfileRefs": arrayDef(refDef("app.cerulia.defs#ruleProfileRef")),
				"outcomeSummary":           stringDef(""),
				"advancementRefs":          arrayDef(refDef("app.cerulia.defs#characterAdvancementRef")),
				"supersedesRef":            refDef("app.cerulia.defs#characterEpisodeRef"),
				"recordedByDid":            refDef("app.cerulia.defs#did"),
				"createdAt":                refDef("app.cerulia.defs#datetime"),
				"requestId":                refDef("app.cerulia.defs#requestId"),
			},
		),
		"lexicon/app.cerulia.core.publication.json": appendOnlyRecord(
			"app.cerulia.core.publication",
			[]string{"subjectRef", "subjectKind", "entryUrl", "preferredSurfaceKind", "surfaces", "status", "publishedByDid", "publishedAt", "requestId"},
			map[string]any{
				"subjectRef":           refDef("app.cerulia.defs#subjectRef"),
				"subjectKind":          refDef("app.cerulia.defs#publicationSubjectKind"),
				"reuseGrantRef":        refDef("app.cerulia.defs#reuseGrantRef"),
				"entryUrl":             stringDef("uri"),
				"preferredSurfaceKind": refDef("app.cerulia.defs#publicationSurfaceKind"),
				"surfaces":             arrayDefMin(refDef("app.cerulia.defs#surfaceDescriptor"), 1),
				"status":               refDef("app.cerulia.defs#publicationStatus"),
				"supersedesRef":        refDef("app.cerulia.defs#publicationRef"),
				"publishedByDid":       refDef("app.cerulia.defs#did"),
				"publishedAt":          refDef("app.cerulia.defs#datetime"),
				"retiredAt":            refDef("app.cerulia.defs#datetime"),
				"requestId":            refDef("app.cerulia.defs#requestId"),
				"note":                 stringDef(""),
			},
		),
		"lexicon/app.cerulia.core.reuseGrant.json": appendOnlyRecord(
			"app.cerulia.core.reuseGrant",
			[]string{"characterBranchRef", "sourceCampaignRef", "targetKind", "reuseMode", "grantedByDid", "grantedAt", "requestId"},
			map[string]any{
				"characterBranchRef": refDef("app.cerulia.defs#characterBranchRef"),
				"sourceCampaignRef":  refDef("app.cerulia.defs#sourceCampaignRef"),
				"targetKind":         refDef("app.cerulia.defs#reuseTargetKind"),
				"targetRef":          refDef("app.cerulia.defs#targetRef"),
				"targetDid":          refDef("app.cerulia.defs#targetDid"),
				"reuseMode":          refDef("app.cerulia.defs#reuseMode"),
				"revokesRef":         refDef("app.cerulia.defs#reuseGrantRef"),
				"grantedByDid":       refDef("app.cerulia.defs#did"),
				"grantedAt":          refDef("app.cerulia.defs#datetime"),
				"expiresAt":          refDef("app.cerulia.defs#datetime"),
				"revokedAt":          refDef("app.cerulia.defs#datetime"),
				"revokedByDid":       refDef("app.cerulia.defs#did"),
				"revokeReasonCode":   stringDef(""),
				"requestId":          refDef("app.cerulia.defs#requestId"),
				"note":               stringDef(""),
			},
		),
	}
}
