package contract

func runCatalog() map[string]map[string]any {
	return map[string]map[string]any{
		"lexicon/app.cerulia.run.session.json": stableRecord(
			"app.cerulia.run.session",
			[]string{"sessionId", "title", "visibility", "rulesetNsid", "rulesetManifestRef", "ruleProfileRefs", "authorityRef", "state", "createdAt", "requestId", "stateChangedAt", "stateChangedByDid"},
			map[string]any{
				"sessionId":              stringDef(""),
				"campaignRef":            refDef("app.cerulia.defs#campaignRef"),
				"title":                  stringDef(""),
				"visibility":             refDef("app.cerulia.defs#visibility"),
				"rulesetNsid":            refDef("app.cerulia.defs#rulesetNsid"),
				"rulesetManifestRef":     refDef("app.cerulia.defs#rulesetManifestRef"),
				"ruleProfileRefs":        arrayDef(refDef("app.cerulia.defs#ruleProfileRef")),
				"authorityRef":           refDef("app.cerulia.defs#authorityRef"),
				"state":                  refDef("app.cerulia.defs#sessionState"),
				"createdAt":              refDef("app.cerulia.defs#datetime"),
				"scheduledAt":            refDef("app.cerulia.defs#datetime"),
				"endedAt":                refDef("app.cerulia.defs#datetime"),
				"archivedAt":             refDef("app.cerulia.defs#datetime"),
				"requestId":              refDef("app.cerulia.defs#requestId"),
				"stateChangedAt":         refDef("app.cerulia.defs#datetime"),
				"stateChangedByDid":      refDef("app.cerulia.defs#did"),
				"stateReasonCode":        stringDef(""),
				"visibilityChangedAt":    refDef("app.cerulia.defs#datetime"),
				"visibilityChangedByDid": refDef("app.cerulia.defs#did"),
				"visibilityReasonCode":   stringDef(""),
			},
		),
		"lexicon/app.cerulia.run.sessionAuthority.json": stableRecord(
			"app.cerulia.run.sessionAuthority",
			[]string{"sessionRef", "authorityId", "gmAudienceRef", "controllerDids", "recoveryControllerDids", "transferPolicy", "transferPhase", "requestId", "updatedByDid", "createdAt", "updatedAt"},
			map[string]any{
				"sessionRef":             refDef("app.cerulia.defs#sessionRef"),
				"authorityId":            stringDef(""),
				"gmAudienceRef":          refDef("app.cerulia.defs#gmAudienceRef"),
				"controllerDids":         arrayDefMin(refDef("app.cerulia.defs#did"), 1),
				"recoveryControllerDids": arrayDefMin(refDef("app.cerulia.defs#did"), 1),
				"leaseHolderDid":         refDef("app.cerulia.defs#did"),
				"leaseExpiresAt":         refDef("app.cerulia.defs#datetime"),
				"transferPolicy":         refDef("app.cerulia.defs#transferPolicyKind"),
				"pendingControllerDids":  arrayDef(refDef("app.cerulia.defs#did")),
				"transferPhase":          refDef("app.cerulia.defs#transferPhase"),
				"transferStartedAt":      refDef("app.cerulia.defs#datetime"),
				"transferCompletedAt":    refDef("app.cerulia.defs#datetime"),
				"requestId":              refDef("app.cerulia.defs#requestId"),
				"updatedByDid":           refDef("app.cerulia.defs#did"),
				"changeReasonCode":       stringDef(""),
				"createdAt":              refDef("app.cerulia.defs#datetime"),
				"updatedAt":              refDef("app.cerulia.defs#datetime"),
			},
		),
		"lexicon/app.cerulia.run.membership.json": stableRecord(
			"app.cerulia.run.membership",
			[]string{"sessionRef", "actorDid", "role", "status", "requestId", "statusChangedAt", "statusChangedByDid"},
			map[string]any{
				"sessionRef":         refDef("app.cerulia.defs#sessionRef"),
				"actorDid":           refDef("app.cerulia.defs#did"),
				"role":               refDef("app.cerulia.defs#membershipRole"),
				"status":             refDef("app.cerulia.defs#membershipStatus"),
				"supersedesRef":      refDef("app.cerulia.defs#membershipRef"),
				"invitedByDid":       refDef("app.cerulia.defs#did"),
				"joinedAt":           refDef("app.cerulia.defs#datetime"),
				"leftAt":             refDef("app.cerulia.defs#datetime"),
				"bannedAt":           refDef("app.cerulia.defs#datetime"),
				"requestId":          refDef("app.cerulia.defs#requestId"),
				"statusChangedAt":    refDef("app.cerulia.defs#datetime"),
				"statusChangedByDid": refDef("app.cerulia.defs#did"),
				"statusReasonCode":   stringDef(""),
				"note":               stringDef(""),
			},
		),
	}
}
