package contract

func runCatalog() map[string]map[string]any {
	return map[string]map[string]any{
		"lexicon/app.cerulia.run.session.json": stableRecord(
			"app.cerulia.run.session",
			[]string{"sessionId", "title", "visibility", "rulesetNsid", "rulesetManifestRef", "ruleProfileRefs", "authorityRef", "state", "createdAt", "requestId", "stateChangedAt", "stateChangedByDid"},
			map[string]any{
				"sessionId":              stringDef(""),
				"campaignRef":            refDef("app.cerulia.defs#campaignRef"),
				"title":                  stringDef(""),
				"visibility":             refDef("app.cerulia.defs#visibility"),
				"rulesetNsid":            refDef("app.cerulia.defs#rulesetNsid"),
				"rulesetManifestRef":     refDef("app.cerulia.defs#rulesetManifestRef"),
				"ruleProfileRefs":        arrayDef(refDef("app.cerulia.defs#ruleProfileRef")),
				"authorityRef":           refDef("app.cerulia.defs#authorityRef"),
				"state":                  refDef("app.cerulia.defs#sessionState"),
				"createdAt":              refDef("app.cerulia.defs#datetime"),
				"scheduledAt":            refDef("app.cerulia.defs#datetime"),
				"endedAt":                refDef("app.cerulia.defs#datetime"),
				"archivedAt":             refDef("app.cerulia.defs#datetime"),
				"requestId":              refDef("app.cerulia.defs#requestId"),
				"stateChangedAt":         refDef("app.cerulia.defs#datetime"),
				"stateChangedByDid":      refDef("app.cerulia.defs#did"),
				"stateReasonCode":        stringDef(""),
				"visibilityChangedAt":    refDef("app.cerulia.defs#datetime"),
				"visibilityChangedByDid": refDef("app.cerulia.defs#did"),
				"visibilityReasonCode":   stringDef(""),
			},
		),
		"lexicon/app.cerulia.run.sessionAuthority.json": stableRecord(
			"app.cerulia.run.sessionAuthority",
			[]string{"sessionRef", "authorityId", "gmAudienceRef", "controllerDids", "recoveryControllerDids", "transferPolicy", "transferPhase", "requestId", "updatedByDid", "createdAt", "updatedAt"},
			map[string]any{
				"sessionRef":             refDef("app.cerulia.defs#sessionRef"),
				"authorityId":            stringDef(""),
				"gmAudienceRef":          refDef("app.cerulia.defs#gmAudienceRef"),
				"controllerDids":         arrayDefMin(refDef("app.cerulia.defs#did"), 1),
				"recoveryControllerDids": arrayDefMin(refDef("app.cerulia.defs#did"), 1),
				"leaseHolderDid":         refDef("app.cerulia.defs#did"),
				"leaseExpiresAt":         refDef("app.cerulia.defs#datetime"),
				"transferPolicy":         refDef("app.cerulia.defs#transferPolicyKind"),
				"pendingControllerDids":  arrayDef(refDef("app.cerulia.defs#did")),
				"transferPhase":          refDef("app.cerulia.defs#transferPhase"),
				"transferStartedAt":      refDef("app.cerulia.defs#datetime"),
				"transferCompletedAt":    refDef("app.cerulia.defs#datetime"),
				"requestId":              refDef("app.cerulia.defs#requestId"),
				"updatedByDid":           refDef("app.cerulia.defs#did"),
				"changeReasonCode":       stringDef(""),
				"createdAt":              refDef("app.cerulia.defs#datetime"),
				"updatedAt":              refDef("app.cerulia.defs#datetime"),
			},
		),
		"lexicon/app.cerulia.run.membership.json": stableRecord(
			"app.cerulia.run.membership",
			[]string{"sessionRef", "actorDid", "role", "status", "requestId", "statusChangedAt", "statusChangedByDid"},
			map[string]any{
				"sessionRef":         refDef("app.cerulia.defs#sessionRef"),
				"actorDid":           refDef("app.cerulia.defs#did"),
				"role":               refDef("app.cerulia.defs#membershipRole"),
				"status":             refDef("app.cerulia.defs#membershipStatus"),
				"supersedesRef":      refDef("app.cerulia.defs#membershipRef"),
				"invitedByDid":       refDef("app.cerulia.defs#did"),
				"joinedAt":           refDef("app.cerulia.defs#datetime"),
				"leftAt":             refDef("app.cerulia.defs#datetime"),
				"bannedAt":           refDef("app.cerulia.defs#datetime"),
				"requestId":          refDef("app.cerulia.defs#requestId"),
				"statusChangedAt":    refDef("app.cerulia.defs#datetime"),
				"statusChangedByDid": refDef("app.cerulia.defs#did"),
				"statusReasonCode":   stringDef(""),
				"note":               stringDef(""),
			},
		),
		"lexicon/app.cerulia.run.sessionPublication.json": appendOnlyRecord(
			"app.cerulia.run.sessionPublication",
			[]string{"sessionRef", "publicationRef", "entryUrl", "preferredSurfaceKind", "surfaces", "requestId", "publishedByDid", "publishedAt", "updatedByDid", "updatedAt"},
			map[string]any{
				"sessionRef":           refDef("app.cerulia.defs#sessionRef"),
				"publicationRef":       refDef("app.cerulia.defs#publicationRef"),
				"entryUrl":             stringDef("uri"),
				"replayUrl":            stringDef("uri"),
				"preferredSurfaceKind": refDef("app.cerulia.defs#publicationSurfaceKind"),
				"surfaces":             arrayDef(refDef("app.cerulia.defs#surfaceDescriptor")),
				"supersedesRef":        refDef("app.cerulia.defs#sessionPublicationRef"),
				"requestId":            refDef("app.cerulia.defs#requestId"),
				"publishedByDid":       refDef("app.cerulia.defs#did"),
				"publishedAt":          refDef("app.cerulia.defs#datetime"),
				"updatedByDid":         refDef("app.cerulia.defs#did"),
				"updatedAt":            refDef("app.cerulia.defs#datetime"),
				"retiredAt":            refDef("app.cerulia.defs#datetime"),
				"retireReasonCode":     stringDef(""),
			},
		),
		"lexicon/app.cerulia.run.rulingEvent.json": appendOnlyRecord(
			"app.cerulia.run.rulingEvent",
			[]string{"sessionRef", "actionKind", "actorDid", "rulesetNsid", "rulesetManifestRef", "decisionKind", "resultSummary", "decidedByDid", "requestId", "createdAt"},
			map[string]any{
				"sessionRef":          refDef("app.cerulia.defs#sessionRef"),
				"appealCaseRef":       refDef("app.cerulia.defs#appealCaseRef"),
				"actionKind":          stringDef(""),
				"actorDid":            refDef("app.cerulia.defs#did"),
				"normalizedActionRef": refDef("app.cerulia.defs#targetRef"),
				"rulesetNsid":         refDef("app.cerulia.defs#rulesetNsid"),
				"rulesetManifestRef":  refDef("app.cerulia.defs#rulesetManifestRef"),
				"ruleProfileRefs":     arrayDef(refDef("app.cerulia.defs#ruleProfileRef")),
				"decisionKind":        stringDef(""),
				"audienceRef":         refDef("app.cerulia.defs#audienceRef"),
				"resultSummary":       stringDef(""),
				"detailEnvelopeRef":   refDef("app.cerulia.defs#detailEnvelopeRef"),
				"emittedRecordRefs":   arrayDef(refDef("app.cerulia.defs#targetRef")),
				"supersedesRef":       refDef("app.cerulia.defs#rulingEventRef"),
				"decidedByDid":        refDef("app.cerulia.defs#did"),
				"requestId":           refDef("app.cerulia.defs#requestId"),
				"createdAt":           refDef("app.cerulia.defs#datetime"),
			},
		),
		"lexicon/app.cerulia.run.appealCase.json": stableRecord(
			"app.cerulia.run.appealCase",
			[]string{"sessionRef", "targetRef", "targetKind", "targetRequestId", "affectedActorDid", "requestedOutcomeKind", "openedByDid", "openedAt", "status", "caseRevision", "reviewRevision", "authoritySnapshotRequestId", "controllerTransferPolicyKind", "controllerEligibleDids", "controllerRequiredCount", "controllerReviewDueAt", "requestId"},
			map[string]any{
				"sessionRef":                    refDef("app.cerulia.defs#sessionRef"),
				"targetRef":                     refDef("app.cerulia.defs#targetRef"),
				"targetKind":                    refDef("app.cerulia.defs#appealTargetKind"),
				"targetRequestId":               refDef("app.cerulia.defs#requestId"),
				"affectedActorDid":              refDef("app.cerulia.defs#did"),
				"requestedOutcomeKind":          refDef("app.cerulia.defs#appealRequestedOutcomeKind"),
				"openedByDid":                   refDef("app.cerulia.defs#did"),
				"openedAt":                      refDef("app.cerulia.defs#datetime"),
				"status":                        refDef("app.cerulia.defs#appealStatus"),
				"caseRevision":                  integerDef(),
				"reviewRevision":                integerDef(),
				"authoritySnapshotRequestId":    refDef("app.cerulia.defs#requestId"),
				"controllerTransferPolicyKind":  refDef("app.cerulia.defs#transferPolicyKind"),
				"controllerEligibleDids":        arrayDef(refDef("app.cerulia.defs#did")),
				"controllerRequiredCount":       integerDef(),
				"controllerReviewDueAt":         refDef("app.cerulia.defs#datetime"),
				"blockedReasonCode":             refDef("app.cerulia.defs#appealBlockedReason"),
				"escalatedAt":                   refDef("app.cerulia.defs#datetime"),
				"escalatedByDid":                refDef("app.cerulia.defs#did"),
				"escalateRequestId":             refDef("app.cerulia.defs#requestId"),
				"recoveryEligibleDids":          arrayDef(refDef("app.cerulia.defs#did")),
				"recoveryAuthorityRequestId":    refDef("app.cerulia.defs#requestId"),
				"resolvedAt":                    refDef("app.cerulia.defs#datetime"),
				"resolvedByDid":                 refDef("app.cerulia.defs#did"),
				"handoffSummary":                stringDef(""),
				"resultSummary":                 stringDef(""),
				"reviewOutcomeSummary":          stringDef(""),
				"detailEnvelopeRef":             refDef("app.cerulia.defs#detailEnvelopeRef"),
				"withdrawnByDid":                refDef("app.cerulia.defs#did"),
				"withdrawnAt":                   refDef("app.cerulia.defs#datetime"),
				"withdrawRequestId":             refDef("app.cerulia.defs#requestId"),
				"controllerResolutionRequestId": refDef("app.cerulia.defs#requestId"),
				"recoveryResolutionRequestId":   refDef("app.cerulia.defs#requestId"),
				"requestId":                     refDef("app.cerulia.defs#requestId"),
				"note":                          stringDef(""),
			},
		),
		"lexicon/app.cerulia.run.appealReviewEntry.json": appendOnlyRecord(
			"app.cerulia.run.appealReviewEntry",
			[]string{"appealCaseRef", "sessionRef", "reviewPhaseKind", "reviewerDid", "reviewDecisionKind", "caseRevision", "reviewRevision", "requestId", "createdAt"},
			map[string]any{
				"appealCaseRef":      refDef("app.cerulia.defs#appealCaseRef"),
				"sessionRef":         refDef("app.cerulia.defs#sessionRef"),
				"reviewPhaseKind":    refDef("app.cerulia.defs#appealReviewPhaseKind"),
				"reviewerDid":        refDef("app.cerulia.defs#did"),
				"reviewDecisionKind": refDef("app.cerulia.defs#appealReviewDecisionKind"),
				"caseRevision":       integerDef(),
				"reviewRevision":     integerDef(),
				"supersedesRef":      refDef("app.cerulia.defs#appealReviewEntryRef"),
				"detailEnvelopeRef":  refDef("app.cerulia.defs#detailEnvelopeRef"),
				"requestId":          refDef("app.cerulia.defs#requestId"),
				"note":               stringDef(""),
				"createdAt":          refDef("app.cerulia.defs#datetime"),
			},
		),
	}
}
