package contract

func runCatalog() map[string]map[string]any {
	return map[string]map[string]any{
		"lexicon/app.cerulia.run.session.json": stableRecord(
			"app.cerulia.run.session",
			[]string{"sessionId", "title", "visibility", "rulesetNsid", "rulesetManifestRef", "ruleProfileRefs", "authorityRef", "state", "createdAt", "requestId", "stateChangedAt", "stateChangedByDid"},
			map[string]any{
				"sessionId":              stringDef(""),
				"campaignRef":            refDef("app.cerulia.defs#campaignRef"),
				"title":                  stringDef(""),
				"visibility":             refDef("app.cerulia.defs#visibility"),
				"rulesetNsid":            refDef("app.cerulia.defs#rulesetNsid"),
				"rulesetManifestRef":     refDef("app.cerulia.defs#rulesetManifestRef"),
				"ruleProfileRefs":        arrayDef(refDef("app.cerulia.defs#ruleProfileRef")),
				"authorityRef":           refDef("app.cerulia.defs#authorityRef"),
				"state":                  refDef("app.cerulia.defs#sessionState"),
				"createdAt":              refDef("app.cerulia.defs#datetime"),
				"scheduledAt":            refDef("app.cerulia.defs#datetime"),
				"endedAt":                refDef("app.cerulia.defs#datetime"),
				"archivedAt":             refDef("app.cerulia.defs#datetime"),
				"requestId":              refDef("app.cerulia.defs#requestId"),
				"stateChangedAt":         refDef("app.cerulia.defs#datetime"),
				"stateChangedByDid":      refDef("app.cerulia.defs#did"),
				"stateReasonCode":        stringDef(""),
				"visibilityChangedAt":    refDef("app.cerulia.defs#datetime"),
				"visibilityChangedByDid": refDef("app.cerulia.defs#did"),
				"visibilityReasonCode":   stringDef(""),
			},
		),
		"lexicon/app.cerulia.run.sessionAuthority.json": stableRecord(
			"app.cerulia.run.sessionAuthority",
			[]string{"sessionRef", "authorityId", "gmAudienceRef", "controllerDids", "recoveryControllerDids", "transferPolicy", "transferPhase", "requestId", "updatedByDid", "createdAt", "updatedAt"},
			map[string]any{
				"sessionRef":             refDef("app.cerulia.defs#sessionRef"),
				"authorityId":            stringDef(""),
				"gmAudienceRef":          refDef("app.cerulia.defs#gmAudienceRef"),
				"controllerDids":         arrayDefMin(refDef("app.cerulia.defs#did"), 1),
				"recoveryControllerDids": arrayDefMin(refDef("app.cerulia.defs#did"), 1),
				"leaseHolderDid":         refDef("app.cerulia.defs#did"),
				"leaseExpiresAt":         refDef("app.cerulia.defs#datetime"),
				"transferPolicy":         refDef("app.cerulia.defs#transferPolicyKind"),
				"pendingControllerDids":  arrayDef(refDef("app.cerulia.defs#did")),
				"transferPhase":          refDef("app.cerulia.defs#transferPhase"),
				"transferStartedAt":      refDef("app.cerulia.defs#datetime"),
				"transferCompletedAt":    refDef("app.cerulia.defs#datetime"),
				"requestId":              refDef("app.cerulia.defs#requestId"),
				"updatedByDid":           refDef("app.cerulia.defs#did"),
				"changeReasonCode":       stringDef(""),
				"createdAt":              refDef("app.cerulia.defs#datetime"),
				"updatedAt":              refDef("app.cerulia.defs#datetime"),
			},
		),
		"lexicon/app.cerulia.run.membership.json": stableRecord(
			"app.cerulia.run.membership",
			[]string{"sessionRef", "actorDid", "role", "status", "requestId", "statusChangedAt", "statusChangedByDid"},
			map[string]any{
				"sessionRef":         refDef("app.cerulia.defs#sessionRef"),
				"actorDid":           refDef("app.cerulia.defs#did"),
				"role":               refDef("app.cerulia.defs#membershipRole"),
				"status":             refDef("app.cerulia.defs#membershipStatus"),
				"supersedesRef":      refDef("app.cerulia.defs#membershipRef"),
				"invitedByDid":       refDef("app.cerulia.defs#did"),
				"joinedAt":           refDef("app.cerulia.defs#datetime"),
				"leftAt":             refDef("app.cerulia.defs#datetime"),
				"bannedAt":           refDef("app.cerulia.defs#datetime"),
				"requestId":          refDef("app.cerulia.defs#requestId"),
				"statusChangedAt":    refDef("app.cerulia.defs#datetime"),
				"statusChangedByDid": refDef("app.cerulia.defs#did"),
				"statusReasonCode":   stringDef(""),
				"note":               stringDef(""),
			},
		),
		"lexicon/app.cerulia.run.sessionPublication.json": appendOnlyRecord(
			"app.cerulia.run.sessionPublication",
			[]string{"sessionRef", "publicationRef", "entryUrl", "preferredSurfaceKind", "surfaces", "requestId", "publishedByDid", "publishedAt", "updatedByDid", "updatedAt"},
			map[string]any{
				"sessionRef":           refDef("app.cerulia.defs#sessionRef"),
				"publicationRef":       refDef("app.cerulia.defs#publicationRef"),
				"entryUrl":             stringDef("uri"),
				"replayUrl":            stringDef("uri"),
				"preferredSurfaceKind": refDef("app.cerulia.defs#publicationSurfaceKind"),
				"surfaces":             arrayDef(refDef("app.cerulia.defs#surfaceDescriptor")),
				"supersedesRef":        refDef("app.cerulia.defs#sessionPublicationRef"),
				"requestId":            refDef("app.cerulia.defs#requestId"),
				"publishedByDid":       refDef("app.cerulia.defs#did"),
				"publishedAt":          refDef("app.cerulia.defs#datetime"),
				"updatedByDid":         refDef("app.cerulia.defs#did"),
				"updatedAt":            refDef("app.cerulia.defs#datetime"),
				"retiredAt":            refDef("app.cerulia.defs#datetime"),
				"retireReasonCode":     stringDef(""),
			},
		),
		"lexicon/app.cerulia.run.characterInstance.json": stableRecord(
			"app.cerulia.run.characterInstance",
			[]string{"sessionRef", "instanceLabel", "sourceType", "controllerDids", "requestId", "createdAt", "updatedByDid", "updatedAt"},
			map[string]any{
				"sessionRef":            refDef("app.cerulia.defs#sessionRef"),
				"baseSheetRef":          refDef("app.cerulia.defs#characterSheetRef"),
				"characterBranchRef":    refDef("app.cerulia.defs#characterBranchRef"),
				"instanceLabel":         stringDef(""),
				"sourceType":            refDef("app.cerulia.defs#sourceType"),
				"controllerDids":        arrayDefMin(refDef("app.cerulia.defs#did"), 1),
				"controllerAudienceRef": refDef("app.cerulia.defs#controllerAudienceRef"),
				"defaultTokenRef":       refDef("app.cerulia.defs#tokenRef"),
				"requestId":             refDef("app.cerulia.defs#requestId"),
				"createdAt":             refDef("app.cerulia.defs#datetime"),
				"retiredAt":             refDef("app.cerulia.defs#datetime"),
				"updatedByDid":          refDef("app.cerulia.defs#did"),
				"updatedAt":             refDef("app.cerulia.defs#datetime"),
			},
		),
		"lexicon/app.cerulia.run.characterState.json": stableRecord(
			"app.cerulia.run.characterState",
			[]string{"sessionRef", "characterInstanceRef", "requestId", "revision", "updatedByDid", "updatedAt"},
			map[string]any{
				"sessionRef":              refDef("app.cerulia.defs#sessionRef"),
				"characterInstanceRef":    refDef("app.cerulia.defs#characterInstanceRef"),
				"publicResources":         map[string]any{"type": "object"},
				"publicStatuses":          arrayDef(stringDef("")),
				"privateStateEnvelopeRef": refDef("app.cerulia.defs#privateStateEnvelopeRef"),
				"sceneRef":                refDef("app.cerulia.defs#sceneRef"),
				"initiative":              integerDef(),
				"requestId":               refDef("app.cerulia.defs#requestId"),
				"revision":                integerDef(),
				"updatedByDid":            refDef("app.cerulia.defs#did"),
				"updatedAt":               refDef("app.cerulia.defs#datetime"),
			},
		),
		"lexicon/app.cerulia.run.message.json": appendOnlyRecord(
			"app.cerulia.run.message",
			[]string{"sessionRef", "authorDid", "channelKind", "requestId", "createdAt"},
			map[string]any{
				"sessionRef":        refDef("app.cerulia.defs#sessionRef"),
				"authorDid":         refDef("app.cerulia.defs#did"),
				"channelKind":       stringDef(""),
				"audienceRef":       refDef("app.cerulia.defs#audienceRef"),
				"bodyText":          stringDef(""),
				"secretEnvelopeRef": refDef("app.cerulia.defs#secretEnvelopeRef"),
				"replyToRef":        refDef("app.cerulia.defs#messageRef"),
				"requestId":         refDef("app.cerulia.defs#requestId"),
				"clientNonce":       stringDef(""),
				"createdAt":         refDef("app.cerulia.defs#datetime"),
			},
		),
		"lexicon/app.cerulia.run.roll.json": appendOnlyRecord(
			"app.cerulia.run.roll",
			[]string{"sessionRef", "actorDid", "command", "resultSummary", "requestId", "createdAt"},
			map[string]any{
				"sessionRef":        refDef("app.cerulia.defs#sessionRef"),
				"actorDid":          refDef("app.cerulia.defs#did"),
				"command":           stringDef(""),
				"normalizedCommand": stringDef(""),
				"resultSummary":     stringDef(""),
				"detailPayload":     map[string]any{"type": "unknown"},
				"targetRef":         refDef("app.cerulia.defs#targetRef"),
				"audienceRef":       refDef("app.cerulia.defs#audienceRef"),
				"secretEnvelopeRef": refDef("app.cerulia.defs#secretEnvelopeRef"),
				"requestId":         refDef("app.cerulia.defs#requestId"),
				"rngVersion":        stringDef(""),
				"createdAt":         refDef("app.cerulia.defs#datetime"),
			},
		),
		"lexicon/app.cerulia.run.rulingEvent.json": appendOnlyRecord(
			"app.cerulia.run.rulingEvent",
			[]string{"sessionRef", "actionKind", "actorDid", "rulesetNsid", "rulesetManifestRef", "decisionKind", "resultSummary", "decidedByDid", "requestId", "createdAt"},
			map[string]any{
				"sessionRef":          refDef("app.cerulia.defs#sessionRef"),
				"appealCaseRef":       refDef("app.cerulia.defs#appealCaseRef"),
				"actionKind":          stringDef(""),
				"actorDid":            refDef("app.cerulia.defs#did"),
				"normalizedActionRef": refDef("app.cerulia.defs#targetRef"),
				"rulesetNsid":         refDef("app.cerulia.defs#rulesetNsid"),
				"rulesetManifestRef":  refDef("app.cerulia.defs#rulesetManifestRef"),
				"ruleProfileRefs":     arrayDef(refDef("app.cerulia.defs#ruleProfileRef")),
				"decisionKind":        stringDef(""),
				"audienceRef":         refDef("app.cerulia.defs#audienceRef"),
				"resultSummary":       stringDef(""),
				"detailEnvelopeRef":   refDef("app.cerulia.defs#detailEnvelopeRef"),
				"emittedRecordRefs":   arrayDef(refDef("app.cerulia.defs#targetRef")),
				"supersedesRef":       refDef("app.cerulia.defs#rulingEventRef"),
				"decidedByDid":        refDef("app.cerulia.defs#did"),
				"requestId":           refDef("app.cerulia.defs#requestId"),
				"createdAt":           refDef("app.cerulia.defs#datetime"),
			},
		),
		"lexicon/app.cerulia.run.appealCase.json": stableRecord(
			"app.cerulia.run.appealCase",
			[]string{"sessionRef", "targetRef", "targetKind", "targetRequestId", "affectedActorDid", "requestedOutcomeKind", "openedByDid", "openedAt", "status", "caseRevision", "reviewRevision", "authoritySnapshotRequestId", "controllerTransferPolicyKind", "controllerEligibleDids", "controllerRequiredCount", "controllerReviewDueAt", "requestId"},
			map[string]any{
				"sessionRef":                    refDef("app.cerulia.defs#sessionRef"),
				"targetRef":                     refDef("app.cerulia.defs#targetRef"),
				"targetKind":                    refDef("app.cerulia.defs#appealTargetKind"),
				"targetRequestId":               refDef("app.cerulia.defs#requestId"),
				"affectedActorDid":              refDef("app.cerulia.defs#did"),
				"requestedOutcomeKind":          refDef("app.cerulia.defs#appealRequestedOutcomeKind"),
				"openedByDid":                   refDef("app.cerulia.defs#did"),
				"openedAt":                      refDef("app.cerulia.defs#datetime"),
				"status":                        refDef("app.cerulia.defs#appealStatus"),
				"caseRevision":                  integerDef(),
				"reviewRevision":                integerDef(),
				"authoritySnapshotRequestId":    refDef("app.cerulia.defs#requestId"),
				"controllerTransferPolicyKind":  refDef("app.cerulia.defs#transferPolicyKind"),
				"controllerEligibleDids":        arrayDef(refDef("app.cerulia.defs#did")),
				"controllerRequiredCount":       integerDef(),
				"controllerReviewDueAt":         refDef("app.cerulia.defs#datetime"),
				"blockedReasonCode":             refDef("app.cerulia.defs#appealBlockedReason"),
				"escalatedAt":                   refDef("app.cerulia.defs#datetime"),
				"escalatedByDid":                refDef("app.cerulia.defs#did"),
				"escalateRequestId":             refDef("app.cerulia.defs#requestId"),
				"recoveryEligibleDids":          arrayDef(refDef("app.cerulia.defs#did")),
				"recoveryAuthorityRequestId":    refDef("app.cerulia.defs#requestId"),
				"resolvedAt":                    refDef("app.cerulia.defs#datetime"),
				"resolvedByDid":                 refDef("app.cerulia.defs#did"),
				"handoffSummary":                stringDef(""),
				"resultSummary":                 stringDef(""),
				"reviewOutcomeSummary":          stringDef(""),
				"detailEnvelopeRef":             refDef("app.cerulia.defs#detailEnvelopeRef"),
				"withdrawnByDid":                refDef("app.cerulia.defs#did"),
				"withdrawnAt":                   refDef("app.cerulia.defs#datetime"),
				"withdrawRequestId":             refDef("app.cerulia.defs#requestId"),
				"controllerResolutionRequestId": refDef("app.cerulia.defs#requestId"),
				"recoveryResolutionRequestId":   refDef("app.cerulia.defs#requestId"),
				"requestId":                     refDef("app.cerulia.defs#requestId"),
				"note":                          stringDef(""),
			},
		),
		"lexicon/app.cerulia.run.appealReviewEntry.json": appendOnlyRecord(
			"app.cerulia.run.appealReviewEntry",
			[]string{"appealCaseRef", "sessionRef", "reviewPhaseKind", "reviewerDid", "reviewDecisionKind", "caseRevision", "reviewRevision", "requestId", "createdAt"},
			map[string]any{
				"appealCaseRef":      refDef("app.cerulia.defs#appealCaseRef"),
				"sessionRef":         refDef("app.cerulia.defs#sessionRef"),
				"reviewPhaseKind":    refDef("app.cerulia.defs#appealReviewPhaseKind"),
				"reviewerDid":        refDef("app.cerulia.defs#did"),
				"reviewDecisionKind": refDef("app.cerulia.defs#appealReviewDecisionKind"),
				"caseRevision":       integerDef(),
				"reviewRevision":     integerDef(),
				"supersedesRef":      refDef("app.cerulia.defs#appealReviewEntryRef"),
				"detailEnvelopeRef":  refDef("app.cerulia.defs#detailEnvelopeRef"),
				"requestId":          refDef("app.cerulia.defs#requestId"),
				"note":               stringDef(""),
				"createdAt":          refDef("app.cerulia.defs#datetime"),
			},
		),
		"lexicon/app.cerulia.secret.audience.json": stableRecord(
			"app.cerulia.secret.audience",
			[]string{"sessionRef", "audienceId", "audienceKind", "selectorPolicyKind", "requestId", "keyVersion", "status", "updatedByDid", "createdAt", "updatedAt"},
			map[string]any{
				"sessionRef":              refDef("app.cerulia.defs#sessionRef"),
				"audienceId":              stringDef(""),
				"title":                   stringDef(""),
				"audienceKind":            refDef("app.cerulia.defs#audienceKind"),
				"selectorPolicyKind":      refDef("app.cerulia.defs#selectorPolicyKind"),
				"actorDids":               arrayDef(refDef("app.cerulia.defs#did")),
				"roles":                   arrayDef(refDef("app.cerulia.defs#membershipRole")),
				"membershipStatuses":      arrayDef(refDef("app.cerulia.defs#membershipStatus")),
				"sessionStates":           arrayDef(refDef("app.cerulia.defs#sessionState")),
				"snapshotSourceRequestId": refDef("app.cerulia.defs#requestId"),
				"requestId":               refDef("app.cerulia.defs#requestId"),
				"keyVersion":              integerDef(),
				"status":                  refDef("app.cerulia.defs#audienceStatus"),
				"updatedByDid":            refDef("app.cerulia.defs#did"),
				"statusReasonCode":        stringDef(""),
				"createdAt":               refDef("app.cerulia.defs#datetime"),
				"updatedAt":               refDef("app.cerulia.defs#datetime"),
			},
		),
		"lexicon/app.cerulia.secret.audienceGrant.json": stableRecord(
			"app.cerulia.secret.audienceGrant",
			[]string{"audienceRef", "actorDid", "requestId", "keyVersion", "wrappedKey", "grantStatus", "validFrom", "grantedByDid", "updatedAt"},
			map[string]any{
				"audienceRef":      refDef("app.cerulia.defs#audienceRef"),
				"actorDid":         refDef("app.cerulia.defs#did"),
				"requestId":        refDef("app.cerulia.defs#requestId"),
				"keyVersion":       integerDef(),
				"wrappedKey":       stringDef(""),
				"grantStatus":      refDef("app.cerulia.defs#grantStatus"),
				"validFrom":        refDef("app.cerulia.defs#datetime"),
				"grantedByDid":     refDef("app.cerulia.defs#did"),
				"revokedAt":        refDef("app.cerulia.defs#datetime"),
				"revokedByDid":     refDef("app.cerulia.defs#did"),
				"revokeReasonCode": stringDef(""),
				"updatedAt":        refDef("app.cerulia.defs#datetime"),
			},
		),
		"lexicon/app.cerulia.secret.secretEnvelope.json": appendOnlyRecord(
			"app.cerulia.secret.secretEnvelope",
			[]string{"sessionRef", "audienceRef", "payloadType", "cipherSuite", "keyVersion", "contentRef", "contentDigest", "requestId", "createdByDid", "createdAt"},
			map[string]any{
				"sessionRef":    refDef("app.cerulia.defs#sessionRef"),
				"audienceRef":   refDef("app.cerulia.defs#audienceRef"),
				"payloadType":   stringDef(""),
				"cipherSuite":   stringDef(""),
				"keyVersion":    integerDef(),
				"contentRef":    stringDef("uri"),
				"contentDigest": stringDef(""),
				"requestId":     refDef("app.cerulia.defs#requestId"),
				"createdByDid":  refDef("app.cerulia.defs#did"),
				"createdAt":     refDef("app.cerulia.defs#datetime"),
			},
		),
		"lexicon/app.cerulia.secret.revealEvent.json": appendOnlyRecord(
			"app.cerulia.secret.revealEvent",
			[]string{"sessionRef", "subjectRef", "toAudienceRef", "revealMode", "requestId", "performedByDid", "revealedAt"},
			map[string]any{
				"sessionRef":      refDef("app.cerulia.defs#sessionRef"),
				"subjectRef":      refDef("app.cerulia.defs#subjectRef"),
				"fromAudienceRef": refDef("app.cerulia.defs#audienceRef"),
				"toAudienceRef":   refDef("app.cerulia.defs#audienceRef"),
				"revealMode":      refDef("app.cerulia.defs#revealMode"),
				"requestId":       refDef("app.cerulia.defs#requestId"),
				"performedByDid":  refDef("app.cerulia.defs#did"),
				"revealedAt":      refDef("app.cerulia.defs#datetime"),
				"note":            stringDef(""),
			},
		),
		"lexicon/app.cerulia.secret.redactionEvent.json": appendOnlyRecord(
			"app.cerulia.secret.redactionEvent",
			[]string{"sessionRef", "subjectRef", "redactionMode", "requestId", "reasonCode", "performedByDid", "createdAt"},
			map[string]any{
				"sessionRef":     refDef("app.cerulia.defs#sessionRef"),
				"subjectRef":     refDef("app.cerulia.defs#subjectRef"),
				"redactionMode":  refDef("app.cerulia.defs#redactionMode"),
				"replacementRef": refDef("app.cerulia.defs#targetRef"),
				"requestId":      refDef("app.cerulia.defs#requestId"),
				"reasonCode":     stringDef(""),
				"performedByDid": refDef("app.cerulia.defs#did"),
				"createdAt":      refDef("app.cerulia.defs#datetime"),
			},
		),
	}
}
