package contract

func ExampleDocuments() map[string]any {
	return map[string]any{
		"examples/rpc/createCampaign.request.json": map[string]any{
			"title":                  "星見ヶ原キャンペーン",
			"visibility":             "unlisted",
			"rulesetNsid":            "app.cerulia.rules.swords-world",
			"rulesetManifestRef":     "at://did:plc:rules/app.cerulia.core.rulesetManifest/manifest-sw-1",
			"sharedRuleProfileRefs":  []string{"at://did:plc:house/app.cerulia.core.ruleProfile/house-profile-1"},
			"defaultReusePolicyKind": "explicit-cross-campaign",
			"stewardDids":            []string{"did:plc:steward1"},
			"requestId":              "req-create-campaign-001",
		},
		"examples/rpc/createCampaign.response.json": map[string]any{
			"requestId":         "req-create-campaign-001",
			"resultKind":        "accepted",
			"emittedRecordRefs": []string{"at://did:plc:steward1/app.cerulia.core.campaign/campaign-req-create-campaign-001"},
			"currentRevision":   1,
		},
		"examples/rpc/createCharacterBranch.request.json": map[string]any{
			"ownerDid":     "did:plc:owner1",
			"baseSheetRef": "at://did:plc:owner1/app.cerulia.core.characterSheet/sheet-req-import-sheet-001",
			"branchKind":   "campaign-fork",
			"branchLabel":  "星見ヶ原本編",
			"requestId":    "req-create-branch-001",
		},
		"examples/rpc/recordCharacterAdvancement.request.json": map[string]any{
			"characterBranchRef": "at://did:plc:owner1/app.cerulia.core.characterBranch/branch-req-create-branch-001",
			"advancementKind":    "milestone",
			"deltaPayloadRef":    "https://cerulia.example/payloads/milestone-1.json",
			"approvedByDid":      "did:plc:steward1",
			"effectiveAt":        "2026-04-03T00:00:00Z",
			"requestId":          "req-advancement-001",
		},
		"examples/rpc/recordCharacterEpisode.request.json": map[string]any{
			"characterBranchRef":       "at://did:plc:owner1/app.cerulia.core.characterBranch/branch-req-create-branch-001",
			"campaignRef":              "at://did:plc:steward1/app.cerulia.core.campaign/campaign-req-create-campaign-001",
			"scenarioLabel":            "第一話 帰還",
			"rulesetManifestRef":       "at://did:plc:rules/app.cerulia.core.rulesetManifest/manifest-sw-1",
			"effectiveRuleProfileRefs": []string{"at://did:plc:house/app.cerulia.core.ruleProfile/house-profile-1"},
			"outcomeSummary":           "帰還と再契約を確定した。",
			"advancementRefs":          []string{"at://did:plc:owner1/app.cerulia.core.characterAdvancement/advancement-req-advancement-001"},
			"recordedByDid":            "did:plc:owner1",
			"requestId":                "req-episode-001",
		},
		"examples/rpc/publishSubject.request.json": map[string]any{
			"subjectRef":           "at://did:plc:owner1/app.cerulia.core.characterEpisode/episode-req-episode-001",
			"subjectKind":          "character-episode",
			"entryUrl":             "https://cerulia.example/publications/episode-1",
			"preferredSurfaceKind": "app-card",
			"surfaces": []map[string]any{{
				"surfaceKind": "app-card",
				"purposeKind": "stable-entry",
				"surfaceUri":  "https://cerulia.example/publications/episode-1",
				"status":      "active",
			}},
			"requestId": "req-publish-001",
		},
		"examples/rpc/retirePublication.request.json": map[string]any{
			"publicationRef": "at://did:plc:owner1/app.cerulia.core.publication/publication-req-publish-001",
			"requestId":      "req-retire-publication-001",
			"note":           "後続版へ差し替え",
		},
		"examples/rpc/grantReuse.request.json": map[string]any{
			"characterBranchRef": "at://did:plc:owner1/app.cerulia.core.characterBranch/branch-req-create-branch-001",
			"sourceCampaignRef":  "at://did:plc:steward1/app.cerulia.core.campaign/campaign-req-create-campaign-001",
			"targetKind":         "campaign",
			"targetRef":          "at://did:plc:steward2/app.cerulia.core.campaign/campaign-target-001",
			"reuseMode":          "fork-and-advance",
			"requestId":          "req-grant-reuse-001",
		},
		"examples/rpc/revokeReuse.request.json": map[string]any{
			"reuseGrantRef":    "at://did:plc:owner1/app.cerulia.core.reuseGrant/reuse-req-grant-reuse-001",
			"revokeReasonCode": "scope-closed",
			"requestId":        "req-revoke-reuse-001",
		},
		"examples/rpc/getCharacterHome.response.json": map[string]any{
			"ownerDid": "did:plc:owner1",
			"primaryBranch": map[string]any{
				"characterBranchRef": "at://did:plc:owner1/app.cerulia.core.characterBranch/branch-req-create-branch-001",
				"baseSheetRef":       "at://did:plc:owner1/app.cerulia.core.characterSheet/sheet-req-import-sheet-001",
				"branchLabel":        "星見ヶ原本編",
				"branchKind":         "campaign-fork",
				"ownerDid":           "did:plc:owner1",
				"revision":           1,
			},
			"branches": []map[string]any{{
				"characterBranchRef": "at://did:plc:owner1/app.cerulia.core.characterBranch/branch-req-create-branch-001",
				"baseSheetRef":       "at://did:plc:owner1/app.cerulia.core.characterSheet/sheet-req-import-sheet-001",
				"branchLabel":        "星見ヶ原本編",
				"branchKind":         "campaign-fork",
				"ownerDid":           "did:plc:owner1",
				"revision":           1,
			}},
			"recentEpisodes": []map[string]any{},
			"recentConversions": []map[string]any{},
			"reuseGrants":    []map[string]any{},
			"publications":   []map[string]any{},
			"linkedCampaigns": []map[string]any{},
		},
		"examples/rpc/getCampaignView.response.json": map[string]any{
			"mode": "owner-steward",
			"campaign": map[string]any{
				"campaignRef": "at://did:plc:steward1/app.cerulia.core.campaign/campaign-req-create-campaign-001",
				"title":       "星見ヶ原キャンペーン",
				"visibility":  "unlisted",
			},
			"publishedArtifacts": []map[string]any{},
		},
		"examples/rpc/listPublications.response.json": map[string]any{
			"items": []map[string]any{},
		},
	}
}
