package contract

func ExampleDocuments() map[string]any {
	return map[string]any{
		"examples/rpc/createCampaign.request.json": map[string]any{
			"title":                  "星見ヶ原キャンペーン",
			"visibility":             "unlisted",
			"rulesetNsid":            "app.cerulia.rules.swords-world",
			"rulesetManifestRef":     "at://did:plc:rules/app.cerulia.core.rulesetManifest/manifest-sw-1",
			"sharedRuleProfileRefs":  []string{"at://did:plc:house/app.cerulia.core.ruleProfile/house-profile-1"},
			"defaultReusePolicyKind": "explicit-cross-campaign",
			"stewardDids":            []string{"did:plc:steward1"},
			"requestId":              "req-create-campaign-001",
		},
		"examples/rpc/createCampaign.response.json": map[string]any{
			"requestId":         "req-create-campaign-001",
			"resultKind":        "accepted",
			"emittedRecordRefs": []string{"at://did:plc:steward1/app.cerulia.core.campaign/main"},
			"currentRevision":   1,
		},
		"examples/rpc/createCharacterBranch.request.json": map[string]any{
			"ownerDid":     "did:plc:owner1",
			"baseSheetRef": "at://did:plc:owner1/app.cerulia.core.characterSheet/hero",
			"branchKind":   "campaign-fork",
			"branchLabel":  "星見ヶ原本編",
			"requestId":    "req-create-branch-001",
		},
		"examples/rpc/recordCharacterAdvancement.request.json": map[string]any{
			"characterBranchRef": "at://did:plc:owner1/app.cerulia.core.characterBranch/starfield",
			"advancementKind":    "milestone",
			"deltaPayloadRef":    "at://did:plc:owner1/app.cerulia.blob.delta/milestone-1",
			"approvedByDid":      "did:plc:steward1",
			"effectiveAt":        "2026-04-03T00:00:00Z",
			"requestId":          "req-advancement-001",
		},
		"examples/rpc/recordCharacterEpisode.request.json": map[string]any{
			"characterBranchRef":       "at://did:plc:owner1/app.cerulia.core.characterBranch/starfield",
			"campaignRef":              "at://did:plc:steward1/app.cerulia.core.campaign/main",
			"scenarioLabel":            "第一話 帰還",
			"rulesetManifestRef":       "at://did:plc:rules/app.cerulia.core.rulesetManifest/manifest-sw-1",
			"effectiveRuleProfileRefs": []string{"at://did:plc:house/app.cerulia.core.ruleProfile/house-profile-1"},
			"outcomeSummary":           "帰還と再契約を確定した。",
			"advancementRefs":          []string{"at://did:plc:owner1/app.cerulia.core.characterAdvancement/3k4i5j"},
			"recordedByDid":            "did:plc:owner1",
			"requestId":                "req-episode-001",
		},
		"examples/rpc/publishSubject.request.json": map[string]any{
			"subjectRef":           "at://did:plc:owner1/app.cerulia.core.characterEpisode/3k4i5j",
			"subjectKind":          "character-episode",
			"entryUrl":             "https://cerulia.example/publications/episode-1",
			"preferredSurfaceKind": "app-card",
			"surfaces": []map[string]any{{
				"surfaceKind": "app-card",
				"purposeKind": "stable-entry",
				"surfaceUri":  "https://cerulia.example/publications/episode-1",
				"status":      "active",
			}},
			"requestId": "req-publish-001",
		},
		"examples/rpc/retirePublication.request.json": map[string]any{
			"publicationRef": "at://did:plc:owner1/app.cerulia.core.publication/3k4i5j",
			"requestId":      "req-retire-publication-001",
			"note":           "後続版へ差し替え",
		},
		"examples/rpc/getCharacterHome.response.json": map[string]any{
			"ownerDid": "did:plc:owner1",
			"primaryBranch": map[string]any{
				"characterBranchRef": "at://did:plc:owner1/app.cerulia.core.characterBranch/starfield",
				"baseSheetRef":       "at://did:plc:owner1/app.cerulia.core.characterSheet/hero",
				"branchLabel":        "星見ヶ原本編",
				"branchKind":         "campaign-fork",
				"ownerDid":           "did:plc:owner1",
				"revision":           1,
			},
			"branches":       []map[string]any{},
			"recentEpisodes": []map[string]any{},
			"reuseGrants":    []map[string]any{},
			"publications":   []map[string]any{},
		},
		"examples/rpc/getCampaignView.response.json": map[string]any{
			"mode": "owner-steward",
			"campaign": map[string]any{
				"campaignRef": "at://did:plc:steward1/app.cerulia.core.campaign/main",
				"title":       "星見ヶ原キャンペーン",
				"visibility":  "unlisted",
			},
			"publishedArtifacts": []map[string]any{},
		},
		"examples/rpc/listPublications.response.json": map[string]any{
			"items": []map[string]any{},
		},
		"examples/rpc/exportServiceLog.response.json": map[string]any{
			"items": []map[string]any{},
		},
		"examples/rpc/createSessionDraft.request.json": map[string]any{
			"sessionId":                  "session-starfield-001",
			"campaignRef":                "at://did:plc:steward1/app.cerulia.core.campaign/main",
			"title":                      "星見ヶ原 第1卓",
			"visibility":                 "unlisted",
			"rulesetNsid":                "app.cerulia.rules.swords-world",
			"rulesetManifestRef":         "at://did:plc:rules/app.cerulia.core.rulesetManifest/manifest-sw-1",
			"ruleProfileRefs":            []string{"at://did:plc:house/app.cerulia.core.ruleProfile/house-profile-1"},
			"controllerDids":             []string{"did:plc:gm1"},
			"recoveryControllerDids":     []string{"did:plc:recovery1"},
			"transferPolicy":             "majority-controllers",
			"expectedRulesetManifestRef": "at://did:plc:rules/app.cerulia.core.rulesetManifest/manifest-sw-1",
			"requestId":                  "req-create-session-001",
		},
		"examples/rpc/getSessionAccessPreflight.response.json": map[string]any{
			"sessionRef":       "at://did:plc:gm1/app.cerulia.run.session/session-starfield-001",
			"decisionKind":     "sign-in",
			"reasonCode":       "anonymous-reader",
			"recommendedRoute": "/signin",
		},
		"examples/rpc/getSessionView.response.json": map[string]any{
			"session": map[string]any{
				"sessionRef":         "at://did:plc:gm1/app.cerulia.run.session/session-starfield-001",
				"title":              "星見ヶ原 第1卓",
				"visibility":         "unlisted",
				"state":              "planning",
				"rulesetManifestRef": "at://did:plc:rules/app.cerulia.core.rulesetManifest/manifest-sw-1",
				"ruleProfileRefs":    []string{},
			},
			"authoritySummary": map[string]any{
				"authorityRef":        "at://did:plc:gm1/app.cerulia.run.sessionAuthority/session-starfield-001",
				"transferPhase":       "stable",
				"authorityHealthKind": "healthy",
				"leaseState":          "active",
			},
			"memberships":  []map[string]any{},
			"handoutCount": 0,
			"appealCount":  0,
		},
		"examples/rpc/publishSessionLink.request.json": map[string]any{
			"sessionRef":                 "at://did:plc:gm1/app.cerulia.run.session/session-starfield-001",
			"publicationRef":             "at://did:plc:owner1/app.cerulia.core.publication/publication-1",
			"expectedPublicationHeadRef": "at://did:plc:owner1/app.cerulia.core.publication/publication-1",
			"entryUrl":                   "https://cerulia.example/sessions/starfield",
			"replayUrl":                  "https://cerulia.example/sessions/starfield/replay",
			"preferredSurfaceKind":       "app-card",
			"surfaces": []map[string]any{{
				"surfaceKind": "app-card",
				"purposeKind": "stable-entry",
				"surfaceUri":  "https://cerulia.example/sessions/starfield",
				"status":      "active",
			}},
			"requestId": "req-publish-session-link-001",
		},
		"examples/rpc/submitAppeal.request.json": map[string]any{
			"sessionRef":           "at://did:plc:gm1/app.cerulia.run.session/session-starfield-001",
			"targetKind":           "membership",
			"targetRef":            "at://did:plc:gm1/app.cerulia.run.membership/membership-req-remove-001",
			"targetRequestId":      "req-remove-001",
			"affectedActorDid":     "did:plc:player1",
			"requestedOutcomeKind": "restore-membership",
			"requestId":            "req-submit-appeal-001",
		},
		"examples/rpc/reviewAppeal.request.json": map[string]any{
			"appealCaseRef":          "at://did:plc:gm1/app.cerulia.run.appealCase/appeal-req-submit-appeal-001",
			"reviewPhaseKind":        "controller-review",
			"reviewDecisionKind":     "approve",
			"expectedCaseRevision":   1,
			"expectedReviewRevision": 0,
			"requestId":              "req-review-appeal-001",
		},
		"examples/rpc/escalateAppeal.request.json": map[string]any{
			"appealCaseRef":          "at://did:plc:gm1/app.cerulia.run.appealCase/appeal-req-submit-appeal-001",
			"expectedCaseRevision":   1,
			"expectedReviewRevision": 0,
			"handoffSummary":         "controller 側で quorum が組めなかったため recovery review へ移行した。",
			"requestId":              "req-escalate-appeal-001",
		},
		"examples/rpc/resolveAppeal.request.json": map[string]any{
			"appealCaseRef":          "at://did:plc:gm1/app.cerulia.run.appealCase/appeal-req-submit-appeal-001",
			"expectedCaseRevision":   1,
			"expectedReviewRevision": 1,
			"decisionKind":           "accepted",
			"resultSummary":          "membership の restore を確定した。",
			"requestId":              "req-resolve-appeal-001",
		},
		"examples/rpc/listSessionPublications.response.json": map[string]any{
			"items": []map[string]any{},
		},
		"examples/rpc/listAppealCases.response.json": map[string]any{
			"items": []map[string]any{},
		},
		"examples/rpc/createCharacterInstance.request.json": map[string]any{
			"sessionRef":     "at://did:plc:gm1/app.cerulia.run.session/session-starfield-001",
			"instanceId":     "hero-main",
			"baseSheetRef":   "at://did:plc:player1/app.cerulia.core.characterSheet/hero",
			"instanceLabel":  "主人公",
			"sourceType":     "player-character",
			"controllerDids": []string{"did:plc:player1"},
			"requestId":      "req-create-instance-001",
		},
		"examples/rpc/createSecretEnvelope.request.json": map[string]any{
			"sessionRef":    "at://did:plc:gm1/app.cerulia.run.session/session-starfield-001",
			"audienceRef":   "at://did:plc:gm1/app.cerulia.secret.audience/session-starfield-001-gm-req-create-session-001",
			"payloadType":   "private-state",
			"cipherSuite":   "xchacha20poly1305",
			"contentRef":    "https://blob.example/secret/state-001",
			"contentDigest": "sha256:example",
			"requestId":     "req-create-secret-envelope-001",
		},
		"examples/rpc/sendMessage.request.json": map[string]any{
			"sessionRef":  "at://did:plc:gm1/app.cerulia.run.session/session-starfield-001",
			"channelKind": "table",
			"bodyText":    "探索を続行する。",
			"requestId":   "req-send-message-001",
		},
	}
}
